# Generated by Django 3.2.5 on 2022-03-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
